baseURL = 'https://foxhoundsk.github.io/'
languageCode = 'en-us'
title = 'As the universe, so the soul'
enableComments = true

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[menus]
  [[menus.main]]
    name = 'posts'
    pageRef = 'posts'
    weight = 10

